highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Vu Chau's Resume
name: Vu Chau
email: vuchteb@gmail.com
email_full: mailto:vuchteb@gmail.com
website: My website
website_full: https://vuchau8592.github.io/website
github: https://github.com/vuchau8592
linkedin: https://www.linkedin.com/in/vu-chau8592/
tel: +358 41 721 0315
tel_full: tel:+358417210315
google_maps: 'https://www.google.com/maps/place/Paimenhuilunpolku+6,+00420+Helsinki/@60.2425955,24.8868355,17z/data=!3m1!4b1!4m5!3m4!1s0x468df633adac9649:0x57a8e8f9884b23c1!8m2!3d60.2425929!4d24.8890242'
address:
  street: Paimenhuilunpolku 6B 23
  postcode: "00420"
  city: Helsinki
  country: Finland
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
